name = "instarishta-profile-relay"
main = "worker/index.js"
compatibility_date = "2026-03-20"
workers_dev = true

[vars]
ALLOWED_ORIGINS = "https://www.instarishta.me,https://instarishta.me,http://localhost:3000,http://127.0.0.1:3000,http://127.0.0.1:5500"

[[kv_namespaces]]
binding = "insta"
id = "b190a206c4e0420eb31545eedd83dba3"
